// Template generated by reactGen

package main

import (
	"github.com/PacktPublishing/Hands-On-Full-Stack-Development-with-Go/Chapter09/reactproject/hello_message"
	"myitcv.io/react"
)

type AppDef struct {
	react.ComponentDef
}

func App() *AppElem {
	return buildAppElem()
}

func (a AppDef) Render() react.Element {
	/*
		Return a react div that hosts a title, as well as our custom hello message component
	*/
	return react.Div(nil,
		react.P(nil,
			react.S("This is my first GopherJS React App."),
		),
		react.H1(nil,
			hellomessage.HelloMessage(hellomessage.HelloMessageProps{Message: "Hello"}),
		),
	)
}
